name: CI
on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
    branches:
      - main
      - develop

jobs:
  Test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc-9
          cmake: true
          ninja: true
          ccache: true
        run: |
          ccache --max-size=1G --compression=true --compression_level=5
        
      - name: Configure Cache
        uses: actions/cache@v3
        key: ubuntu-20.04-ccache
        with:
          path: ~/.ccache
      
      - name: Configure CMake
        run: |
          cmake -S . -B build/ -G "Ninja Multi-Config" -DCMAKE_BUILD_TYPE:STRING=Debug -Dprotobuf_BUILD_TESTS:BOOL=FALSE -DCMAKE_C_COMPILER_LAUNCH=ccache -DCMAKE_CXX_COMPILER_LAUNCH=ccache
      
      - name: Build
        run: |
          cmake --build build/ --config Debug --target all
      
      - name: Test
        working-directory: build/
        run: |
          ctest -C Debug