name: CI
on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
    branches:
      - main
      - develop

jobs:
  Test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup environment
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc-9
          cmake: true
          ninja: true
          ccache: true
          cppcheck: true
      
      - name: Configure ccache
        run: |
          ccache --max-size=1G --set-config=compression=true --set-config=compression_level=5
      
      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ubuntu-20.04-ccache
          restore-keys: ubuntu-20.04-ccache

      - name: Configure cmake
        run: |
          cmake -S . -B build/ -G "Ninja Multi-Config" \
            -DCMAKE_BUILD_TYPE:STRING=Debug \
            -Dprotobuf_BUILD_TESTS:BOOL=FALSE \
            -DABSL_PROPAGATE_CXX_STD:BOOL=TRUE
      
      - name: Build
        run: |
          cmake --build build/ --config Debug --target all
      
      - name: Test
        working-directory: build/
        run: |
          ctest -C Debug